### ISSUE TITLE
Change AWS default Region and customization

### ISSUE THREAD

**Issue by trnh** [clusterinthecloud/support#8]
I can see the default region as eu-west-1 , centos8 , t3a.medium for mgmt node.

Where I can change some of those default settings ?

Thank you

**Comment by milliams** [comment]
After copying `aws/terraform.tfvars.example` to `terraform.tfvars` you can set the variables there. For example, that file might look like:

```ini
private_key_path = "~/.ssh/aws-key"
public_key_path = "~/.ssh/aws-key.pub"
region = "us-west-2"
management_shape = "t3a.large"
```

You can see the names of the variables to set in `aws/variables.tf`.

**Comment by trnh** [comment]
Awesome , i got it now.  Will update the document too.

**Comment by trnh** [comment]
can we control the CITS to launch on a specific VPC and subnet ? also only Centos8 support at the moment ?

**Comment by milliams** [comment]
CitC creates its own VPC and subnet in order to be able to control security rules, DNS etc. We haven't got a plan to change this for now.

Indeed only CentOS 8 is supported for compute nodes as we have to configure each of them separately. If you need a different OS for a compute job, you can use something like Singularity to run a container.
